scheduler:
  use: true
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5176'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_CHILGOK
        username: CIAMS_CHILGOK
        password: CIAMS_CHILGOK
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_CHILGOK
        username: MS_GIS_CIAMS_CHILGOK
        password: MS_GIS_CIAMS_CHILGOK
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_CHILGOK
        username: MS_MIS_CIAMS_CHILGOK
        password: MS_MIS_CIAMS_CHILGOK
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\chilgok\files

mapstudio:
  url: http://211.171.200.236:10701/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_CHILGOK
        username: CIAMS_CHILGOK
        password: CIAMS_CHILGOK
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_CHILGOK
        username: MS_GIS_CIAMS_CHILGOK
        password: MS_GIS_CIAMS_CHILGOK
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_CHILGOK
        username: MS_MIS_CIAMS_CHILGOK
        password: MS_MIS_CIAMS_CHILGOK
      user-name: system

file:
  path:
    prefix: /data/ciams/chilgok/ciams/files

mapstudio:
  url: http://211.171.200.236:10701/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.19.1.108:5433/CIAMS_CHILGOK
        username: CIAMS_CHILGOK
        password: CIAMS_CHILGOK
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.19.1.108:5433/MS_GIS_CIAMS_CHILGOK
        username: MS_GIS_CIAMS_CHILGOK
        password: MS_GIS_CIAMS_CHILGOK
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.19.1.108:5433/MS_MIS_CIAMS_CHILGOK
        username: MS_MIS_CIAMS_CHILGOK
        password: MS_MIS_CIAMS_CHILGOK
      user-name: system

file:
  path:
    prefix: D:\project\ciams\files

mapstudio:
  url: http://111.19.1.108:10101/mapstudio

---
