scheduler:
  use: false
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5176'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_GIMCHEON
        username: CIAMS_GIMCHEON
        password: CIAMS_GIMCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_GIMCHEON
        username: MS_GIS_CIAMS_GIMCHEON
        password: MS_GIS_CIAMS_GIMCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_GIMCHEON
        username: MS_MIS_CIAMS_GIMCHEON
        password: MS_MIS_CIAMS_GIMCHEON
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\gimcheon\files

mapstudio:
  url: http://211.171.200.236:11011/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_GIMCHEON
        username: CIAMS_GIMCHEON
        password: CIAMS_GIMCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_GIMCHEON
        username: MS_GIS_CIAMS_GIMCHEON
        password: MS_GIS_CIAMS_GIMCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_GIMCHEON
        username: MS_MIS_CIAMS_GIMCHEON
        password: MS_MIS_CIAMS_GIMCHEON
      user-name: system

file:
  path:
    prefix: /data/ciams/gimcheon/ciams/files

mapstudio:
  url: http://211.171.200.236:11011/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.3.11.67:5880/CIAMS_GIMCHEON
        username: CIAMS_GIMCHEON
        password: CIAMS_GIMCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.3.11.67:5880/MS_GIS_CIAMS_GIMCHEON
        username: MS_GIS_CIAMS_GIMCHEON
        password: MS_GIS_CIAMS_GIMCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.3.11.67:5880/MS_MIS_CIAMS_GIMCHEON
        username: MS_MIS_CIAMS_GIMCHEON
        password: MS_MIS_CIAMS_GIMCHEON
      user-name: system

file:
  path:
    prefix: D:\project\ciams\files

mapstudio:
  url: http://111.3.11.67:40880/mapstudio

---
