scheduler:
  use: false
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5176'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_GYEONGJU
        username: CIAMS_GYEONGJU
        password: CIAMS_GYEONGJU
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_GYEONGJU
        username: MS_GIS_CIAMS_GYEONGJU
        password: MS_GIS_CIAMS_GYEONGJU
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_GYEONGJU
        username: MS_MIS_CIAMS_GYEONGJU
        password: MS_MIS_CIAMS_GYEONGJU
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\gyeongju\files

mapstudio:
  url: http://211.171.200.236:10201/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_GYEONGJU
        username: CIAMS_GYEONGJU
        password: CIAMS_GYEONGJU
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_GYEONGJU
        username: MS_GIS_CIAMS_GYEONGJU
        password: MS_GIS_CIAMS_GYEONGJU
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_GYEONGJU
        username: MS_MIS_CIAMS_GYEONGJU
        password: MS_MIS_CIAMS_GYEONGJU
      user-name: system

file:
  path:
    prefix: /data/ciams/gyeongju/ciams/files

mapstudio:
  url: http://localhost:10201/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.2.1.170:5432/CIAMS_GYEONGJU
        username: CIAMS_GYEONGJU
        password: CIAMS_GYEONGJU
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.2.1.170:5432/MS_GIS_CIAMS_GYEONGJU
        username: MS_GIS_CIAMS_GYEONGJU
        password: MS_GIS_CIAMS_GYEONGJU
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://111.2.1.170:5432/MS_MIS_CIAMS_GYEONGJU
        username: MS_MIS_CIAMS_GYEONGJU
        password: MS_MIS_CIAMS_GYEONGJU
      user-name: system

file:
  path:
    prefix: D:\project\ciams\files

mapstudio:
  url: http://localhost:10101/mapstudio

---
