scheduler:
  use: false
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5176'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_CHEORWON
        username: CIAMS_CHEORWON
        password: CIAMS_CHEORWON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_CHEORWON
        username: MS_GIS_CIAMS_CHEORWON
        password: MS_GIS_CIAMS_CHEORWON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_CHEORWON
        username: MS_MIS_CIAMS_CHEORWON
        password: MS_MIS_CIAMS_CHEORWON
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\cheorwon\files

mapstudio:
  url: http://211.171.200.236:10301/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_CHEORWON
        username: CIAMS_CHEORWON
        password: CIAMS_CHEORWON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_CHEORWON
        username: MS_GIS_CIAMS_CHEORWON
        password: MS_GIS_CIAMS_CHEORWON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_CHEORWON
        username: MS_MIS_CIAMS_CHEORWON
        password: MS_MIS_CIAMS_CHEORWON
      user-name: system

file:
  path:
    prefix: /data/ciams/cheorwon/ciams/files

mapstudio:
  url: http://localhost:10301/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5433/CIAMS_CHEORWON
        username: CIAMS_CHEORWON
        password: CIAMS_CHEORWON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5433/MS_GIS_CIAMS_CHEORWON
        username: MS_GIS_CIAMS_CHEORWON
        password: MS_GIS_CIAMS_CHEORWON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5433/MS_MIS_CIAMS_CHEORWON
        username: MS_MIS_CIAMS_CHEORWON
        password: MS_MIS_CIAMS_CHEORWON
      user-name: system

file:
  path:
#    prefix: D:\uitgis\ciams\files
    prefix: D:\project\ciams\files

mapstudio:
  url: http://106.13.2.173:10101/mapstudio

---
