scheduler:
  use: false
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5176'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_HOENGSEONG
        username: CIAMS_HOENGSEONG
        password: CIAMS_HOENGSEONG
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_HOENGSEONG
        username: MS_GIS_CIAMS_HOENGSEONG
        password: MS_GIS_CIAMS_HOENGSEONG
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_HOENGSEONG
        username: MS_MIS_CIAMS_HOENGSEONG
        password: MS_MIS_CIAMS_HOENGSEONG
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\hoengseong\files

mapstudio:
  url: http://211.171.200.236:10401/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_HOENGSEONG
        username: CIAMS_HOENGSEONG
        password: CIAMS_HOENGSEONG
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_HOENGSEONG
        username: MS_GIS_CIAMS_HOENGSEONG
        password: MS_GIS_CIAMS_HOENGSEONG
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_HOENGSEONG
        username: MS_MIS_CIAMS_HOENGSEONG
        password: MS_MIS_CIAMS_HOENGSEONG
      user-name: system

file:
  path:
    prefix: /data/ciams/hoengseong/ciams/files

mapstudio:
  url: http://localhost:10401/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://106.9.100.87:5433/CIAMS
        username: CIAMS
        password: CIAMS
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://106.9.100.87:5433/MS_GIS_CIAMS
        username: MS_GIS_CIAMS
        password: MS_GIS_CIAMS
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://106.9.100.87:5433/MS_MIS_CIAMS
        username: MS_MIS_CIAMS
        password: MS_MIS_CIAMS
      user-name: system

file:
  path:
    prefix: C:\uitgis\ciams\files

mapstudio:
  url: http://106.9.100.87:10101/mapstudio

logging:
  file:
    name: C:/uitgis/ciams/logs/ciams.log

---
