scheduler:
  use: true
  cron: '0 0 3 ? * SUN'

crs:
  prj: 'EPSG:5174'
  use-transform: true
  use-badekas: true

--- # 로컬 환경 (windows - 개인 PC)
spring:
  config.activate.on-profile: local

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/CIAMS_HONGCHEON
        username: CIAMS_HONGCHEON
        password: CIAMS_HONGCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_GIS_CIAMS_HONGCHEON
        username: MS_GIS_CIAMS_HONGCHEON
        password: MS_GIS_CIAMS_HONGCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://211.171.200.236:5432/MS_MIS_CIAMS_HONGCHEON
        username: MS_MIS_CIAMS_HONGCHEON
        password: MS_MIS_CIAMS_HONGCHEON
      user-name: system

file:
  path:
    prefix: D:\uitgis\ciams\hongcheon\files

mapstudio:
  url: http://211.171.200.236:10601/mapstudio

--- # 개발 환경 (ubuntu - 211.171.200.236)
spring:
  config.activate.on-profile: dev

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_HONGCHEON
        username: CIAMS_HONGCHEON
        password: CIAMS_HONGCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_HONGCHEON
        username: MS_GIS_CIAMS_HONGCHEON
        password: MS_GIS_CIAMS_HONGCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_HONGCHEON
        username: MS_MIS_CIAMS_HONGCHEON
        password: MS_MIS_CIAMS_HONGCHEON
      user-name: system

file:
  path:
    prefix: /data/ciams/hongcheon/ciams/files

mapstudio:
  url: http://localhost:10601/mapstudio

--- # 운영 환경 (windows server - localhost)
spring:
  config.activate.on-profile: prod

  datasource:
    ciams:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/CIAMS_HONGCHEON
        username: CIAMS_HONGCHEON
        password: CIAMS_HONGCHEON
    gis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_GIS_CIAMS_HONGCHEON
        username: MS_GIS_CIAMS_HONGCHEON
        password: MS_GIS_CIAMS_HONGCHEON
    mis:
      hikari:
        jdbc-url: jdbc:log4jdbc:postgresql://localhost:5432/MS_MIS_CIAMS_HONGCHEON
        username: MS_MIS_CIAMS_HONGCHEON
        password: MS_MIS_CIAMS_HONGCHEON
      user-name: system

file:
  path:
    prefix: D:\project\ciams\files

mapstudio:
  url: http://106.8.0.184:10101/mapstudio

---
